[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mtth/scratch.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
