winget install -e --id JetBrains.Toolbox
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Microsoft.WindowsTerminal
winget install -e --id Microsoft.BingWallpaper
winget install -e --id Google.Chrome
winget install -e --id Discord.Discord
winget install -e --id Google.Drive
winget install -e --id Zoom.Zoom
winget install -e --id Microsoft.PowerToys
winget install -e --id Git.Git
winget install -e --id Foxit.FoxitReader
winget install -e --id Amazon.Kindle
winget install -e --id SlackTechnologies.Slack
